# Generated by Django 3.1.1 on 2020-09-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0003_auto_20200929_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='startedfrom',
        ),
    ]
