# Generated by Django 3.1.1 on 2020-09-29 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Calc', '0004_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 8, 51, 43, 58960, tzinfo=utc), verbose_name='started from'),
            preserve_default=False,
        ),
    ]
